version: '3.8'

services:
  core_service:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8082}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth-service:8080}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
      - BASE_URL=${BASE_URL:-http://localhost:3000}
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  app_network:
    name: cfx_network
    driver: bridge 