# Example secrets file for CI/CD workflow
# DO NOT fill in actual values here - this is just a template
# Add these secrets in your GitHub repository: Settings -> Secrets and variables -> Actions

# Docker Hub Authentication
DOCKERHUB_USERNAME: "billyvande7"  # Example: billyvande7
DOCKERHUB_TOKEN: "dckr_pat_LAjSC46Rgch9sRy5uluDZCFqQEo" # Generate from Docker Hub -> Settings -> Security -> New Access Token

# ArgoCD Configuration
ARGOCD_TOKEN: "your-argocd-token"             # Get this from your ArgoCD instance
ARGOCD_SERVER: "your-argocd-server-url"       # Example: https://argocd.example.com

# Optional: Additional Secrets
# Add any service-specific secrets here if needed
# AUTH_SERVICE_SECRET: "your-auth-service-secret"
# SHORTENER_SERVICE_SECRET: "your-shortener-service-secret" 