version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - DB_PATH=${DB_PATH:-/data/auth.db}
      - JWT_SECRET=${JWT_SECRET:-your_super_secret_key_change_this_in_production}
      - JWT_EXPIRY=${JWT_EXPIRY:-24h}
      - NODE_SERVICE_URL=${NODE_SERVICE_URL:-http://localhost:3000}
    volumes:
      - url-shortener-data:/data
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8080}/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  app_network:
    name: cfx_network
    external: true  

volumes:
  url-shortener-data: 