apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      serviceAccountName: frontend
      containers:
      - name: app
        securityContext:
          runAsUser: 0