apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-main
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: devops
  podMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false