namespace: inventory

bases:
  - ../base

resources:
  - ingress.yaml

commonLabels:
  layer: backend
  service: shortener-service

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: shortener-service-configmap
    envs:
      - config.env

patches:
  - patch : |-
      - op: replace
        path: /metadata/name
        value: "shortener-service"
    target:
      kind: Namespace
      name: namespace

  - patch : |-
      - op: replace
        path: /metadata/name
        value: "shortener-service"
    target:
      kind: Deployment
      name: app

  - patch: |-
      - op: replace
        path: /metadata/name
        value: "shortener-service"
    target:
      kind: Service
      name: app

  - patch: |-
      - op: replace
        path: /metadata/name
        value: "shortener-service"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/service-account.name: "shortener-service-token"
    target:
      kind: ServiceAccount
      name: app

  - patch: |-
      - op: replace
        path: /metadata/name
        value: "shortener-service-role"
    target:
      kind: ClusterRole
      name: app

  - patch: |-
      - op: replace
        path: /metadata/name
        value: "shortener-service-rolebinding"
    target:
      kind: ClusterRoleBinding
      name: app